{
  "title": "Enzzo",
  "destination": "blog",
  "baseurl": "/",
  "url": "https://souenzzo.com.br/blog",
  "favicon": "/me.jpg",
  "minima": {
    "social-links": {
      "twitter": "souenzzo",
      "github": "souenzzo",
      "linkedin": "souenzzo",
      "telegram": "souenzzo",
      "keybase": "souenzzo",
      "gitlab": {
        "username": "souenzzo",
        "instance": "https://gitlab.com"
      }
    }
  }
}
